DataDog/riot

riot/riot.py

Minor fix for case env printed in summary

fix: use env for result

---

riot/riot.py

Use factory instead of defaults

---

setup.py

PEP 561 compatibility

---

.github/workflows/main.yml
riotfile.py
setup.py

Drop support for Python 3.6

---

.github/workflows/changelog.yml
.github/workflows/main.yml
docs/conf.py
docs/index.rst
docs/release_notes.rst
docs/requirements.txt
riotfile.py
scripts/check-releasenotes

docs: use reno for release notes management

---

.github/workflows/main.yml
riotfile.py
setup.py

3.6 is still the stable version for pypy.

Add support for Python 3.6

---

riot/cli.py
riot/riot.py
tests/data/simple_riotfile.py
tests/test_cli.py

Add option for selecting venvs by pattern

---

.github/workflows/main.yml
riotfile.py
setup.py

Dependent on #79, #82 
Note that currently only pypy3.6 is supported by the github action. 3.7 should be coming soon: https://github.com/pypa/setuptools/issues/2400

Add pypy to test matrix

---

docs/conf.py
docs/configuration.rst
docs/contributing.rst
docs/index.rst
docs/quickstart.rst
docs/requirements.txt
docs/usage.rst
riot/cli.py
riot/riot.py
riotfile.py

A follow up PR will be needed to document each of the cli arguments and options but otherwise this should be a pretty solid starting point.
Resolves #33.

Add user documentation

---

riot/riot.py

Prevents having to pass `cmdargs` around.

Substitute cmdargs earlier

---

riot/riot.py

Now that we have actual data structures the virtual environment creation
can be cleaned up.

Refactor virtualenv naming

---

.github/workflows/main.yml
docs/contributing.rst
riotfile.py

- Add reno commands
- Add documentation serving command
- Add instructions to contributing docs

Add additional commands to riotfile.py

---

tests/test_cli.py

test: remove useless test file

---

riot/riot.py
tests/test_cli.py

The current code broke the environ passing. Add a test and fix it!

fix: make sure venv is passed to subprocess.run

---

riot/riot.py

This makes sure that all command run to build the venv also get access to the
same env var.

refactor: move run_cmd_venv to Session and always export some env var

---

releasenotes/notes/add-version-info-405c35d8f62c7909.yaml
riot/riot.py
tests/test_unit.py

Add new `Interpreter.version_info` function and some version test cases.

Add Interprter.version_info and version test cases

---

.github/workflows/build_deploy.yml

The wheels were not being built properly in CI.

Fix wheels

---

riot/riot.py

This avoids having a shell string to run.

refactor: do not use shell script to activate venv

---

releasenotes/notes/summary-short-hash-7bd8aabde226e14c.yaml
riot/riot.py
tests/test_cli.py
tests/test_integration.py

This allows one to quickly go from a summary of failed commands in CI to running locally.

feat: add short hash to command summary

---

tests/test_cli.py

test: add test for env not passed

---

docs/requirements.txt

it was out of date with `riotfile.py`

chore(docs): update requirements.txt for readthedocs

---

README.md

Refs: https://github.com/badges/shields/issues/8671

Fix Test badge
