DataDog/riot

riot/riot.py
riotfile.py
setup.cfg
tests/test_cli.py

- Enable `ignore_missing_imports` so we don't fail on missing typing for
external libs
- Disallow incomplete defs to make sure we have fully documented type on every
typed function
- Warn on unused configs and ignore directives
- Disallow usage of Any
- Specify files to check

chore(mypy): tweak mypy options and add more typing

---

.github/workflows/main.yml
riotfile.py

It's a bit awkward because a different python is available each time so we need to specify `pys=[3.6, 3.7, 3.8, 3.9]` and then select the one that's available.

Run coverage job with riot

---

riot/cli.py
riot/riot.py
tests/test_cli.py

Adding the ability to provide `--python` to the `riot list` command.
```
$ riot list
test LC_ALL=C.UTF-8 LANG=C.UTF-8 Python 3.6 'pytest' 'pytest-cov' 'mock'
test LC_ALL=C.UTF-8 LANG=C.UTF-8 Python 3.7 'pytest' 'pytest-cov' 'mock'
test LC_ALL=C.UTF-8 LANG=C.UTF-8 Python 3.8 'pytest' 'pytest-cov' 'mock'
test LC_ALL=C.UTF-8 LANG=C.UTF-8 Python 3.9 'pytest' 'pytest-cov' 'mock'
check_format  Python 3.8 'black==20.8b1'
flake8  Python 3.8 'flake8' 'flake8-blind-except' 'flake8-builtins' 'flake8-docstrings' 'flake8-logging-format' 'flake8-rst-docstrings' 'pygments'
typing  Python 3.8 'mypy' 'pytest'
codecov  Python 3.6 'coverage'
codecov  Python 3.7 'coverage'
codecov  Python 3.8 'coverage'
codecov  Python 3.9 'coverage'
docs  Python 3.8 'sphinx==3.3'
```
```
$ riot list --python 3.6
test …
```

Add --python option to riot list command

---

riot/riot.py

The current use of `cp` is more-or-less portable but is broken:
`cp -r foo bar` copies foo as bar the first time but `cp -r foo bar` copies
`foo` *into* `bar` the second time.

fix: do not use cp to copy trees

---

riot/riot.py

riot should just be a serving hatch and not mess with user encoding in any way,
use the system default one.

fix: do not specify encoding

---

riot/cli.py
riot/riot.py
tests/test_cli.py

Following suggestion in https://github.com/DataDog/riot/pull/55#issuecomment-733018232
Now we can do:
```
riot run test -p3.8 -- -k test_run_suites_cmdargs
============================================================================================================================== test session starts ===============================================================================================================================
platform darwin -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/tahir.butt/go/src/github.com/DataDog/riot
plugins: cov-2.10.1
collected 21 items / 17 deselected / 4 selected
tests/test_cli.py .... …
```

Use extra args for cmdargs

---

riot/__init__.py
riotfile.py

This removes the obscure syntax used for picking the latest package.
"latest" isn't the greatest name since this just corresponds to not
specifying a version. It could be taken from the pip cache and not be
the absolute latest.
Fixes #50

Provide latest export

---

riot/cli.py
riot/riot.py
tests/test_cli.py

- Handle riotfiles that don't have .py extension
- Handle execution errors of riotfile.py
Fixes #38

Handle riotfile errors

---

riot/riot.py

This feature breaks the declarative nature of the virtual env building.
If the need for it arises in the future then we can reconsider having
this feature.

Remove callable env values

---

riot/riot.py

Python 2 outputs the version on stderr, not stdout.

fix(interpreter): catch the version for Python 2

---

riot/riot.py

`riot list` has noticeable performance issues as each entry results in a subprocess invocation of a python interpreter.

Cache interpreter version check and path lookup

---

.mergify.yml

This enables automatic merge when the PR matches the branch protection
settings.
The upside of using this is that Mergify will automatically update the pull
request with the base branch before merging. Therefore, we wont't have to press
the `Update branch`, wait for the CI, and then press merge button again to have
a PR that is ready to be merged.
I've added the `automerge` label as a condition for now so we can control the
usage of this feature. Feel free to remove it later when everyone's happy with
this.

Add a minimal Mergify configuration

---

riotfile.py

This allows to run e.g. mypy with Python 3.x, whatever is available.

ci(riot): use Python 3 for non-test env

---

riot/riot.py

There's no need to hide those since .riot is already hidden.

chore: remove leading dot in venv directory name

---

releasenotes/notes/feature-skip-missing-a032464fbeafdc52.yaml
riot/cli.py
riot/riot.py
tests/test_cli.py

Added an option to allow riot to ignore any missing requested Python
interpreters.

feat: add option to skip missing interpreters

---

.mergify.yml

No need for a label, just wait for the number of reviews and branch protection
settings.

ci(mergify): simplify merging condition

---

riot/riot.py

By default, shutil.copytree follows and copy symlinks targets.
Which is exactly not what standard Unix command does.
Well done, Python.

fix(riot): do not copy symlink target

---

releasenotes/notes/add-exitfirst-option-to-run-7bd06dedf87c3180.yaml
riot/cli.py
riot/riot.py
tests/test_cli.py

-x/--exitfirst which are the same arguments used by pytest
disabled by default, but if provided will stop executing any further test
suites after the first one fails
resolves #133

Add riot run -x option to exit after first failure

---

releasenotes/notes/use-system-shell-222f6711f7b17dd4.yaml
riot/riot.py

Update the initialization to accept the default shell set in the system, if that's not found to fall back to `/bin/bash`

use default shell on system

---

riotfile.py

The latest version of mypy uses modular typesheds. So we need to install the appropriate typeshed for each package we rely on.
This change allows us to automatically install any missing typesheds while processing (it is not two steps, mypy will still produce type checking/errors as part of the result from running with these flags)

Install missing mypy types while type checking

---

riot/riot.py
setup.cfg
tests/test_cli.py
tests/test_integration.py
tests/test_unit.py

The logic that infers all the venv instances has been reworked to track parenting of venv instances. Installation of packages via pip now happens in a predefined folder. This helps with deriving the elements that need to go to the `PYTHONPATH` and the `PATH` environment to ensure correct layering of re-used intermediate venvs.

fix: control and track pip install target dirs

---

releasenotes/notes/fix-sitepkgs-3ef98bad9dc20f70.yaml
riot/riot.py
tests/test_cli.py
tests/test_integration.py
tests/test_unit.py

With the idea of adding to the `PYTHONPATH`, each venv layer only needs to install its packages inside the venv instance, thus reducing the number of packages that are installed in each venv instance. We still use the full package spec in the result report for easier identification of all the dependencies used.
This change also fixes propagation and override of environment variables across layers as well as the correct handling of namespace packages.
BREAKING CHANGE: this change implies that package declarations that are used for pinning dependencies will have to be added to each venv layer that requires them.

fix: handling of package installs, env var overrides and namespace packages

---

releasenotes/notes/fix-parent-py-7de74544797e4d4d.yaml
riot/riot.py

A venv should take interpreter information from a parent venv instance
if it has no pys override.

fix: use correct interpreter config for venv instance

---

.gitignore
riot/riot.py
tests/test_cli.py
tests/test_integration.py
tests/test_unit.py

With control over the pip installation prefix there is no need to create venvs other than the base one. This saves a lot of memory and speeds up the task runs.
These are some numbers based on the `riot` test suite when run with `riot run -p3.9 test`
`.riot` folder size: 184 MB
test run time: 63 s
`.riot` folder size: 27 MB
test run time: 34 s
`riot list` works 🙂 
~~~
❯ pipenv run riot list     
test  Python Interpreter(_hint='3.6') 'pytest' 'pytest-cov' 'mock' 'typing-extensions'
test  Python Interpreter(_hint='3.7') 'pytest' 'pytest-cov' 'mock' 'typing-extensions'
test  Python Interpreter(_hint='3.8') 'pytest' 'pytest-cov' 'mock' 'typing-extensions'
test  Python Interpreter(_hint='3.9') 'pytest' 'pytest-cov' 'mock' 'typing-extensions'
black  Python Interpreter(_hint='3') 
fmt  Python …

perf: create base venvs only

---

releasenotes/notes/shell-fix-d6fc7eb1127473e6.yaml
riot/riot.py
tests/test_integration.py

Some the the virtualenv paths generated may include shell special
characters like `[` and `]`. Namely this happens when extras are
provided (eg. `reno[sphinx]`).
This was breaking the virtualenv commands as the shell attempts to
interpret the special characters in the commands. This is fixed by
quoting the strings before we pass them to the shell.
Fixes #148.

Quote paths that might contain special chars

---

releasenotes/notes/fix-spaces-cmdargs-16399f428692f9c4.yaml
riot/riot.py
tests/test_cli.py

This fixes use cases such as:
riot run foobar -- -k 'not test_foobaz'
for:
pytest {cmdargs}
Which is broken right now because it turns out to run:
as:
pytest -k not test_foobaz
This fixes the code by adding '' around each cmdargs item, which turns the
command line into:
pytest '-k' 'not test_foobaz'
Since this whole string is passed to subprocess with shell=True, we're sure
that shell does not try to interpolate anything.
That sounds safe and neat.

fix: add quotes around cmdargs

---

.github/workflows/main.yml

The pypy3 version seems to refere to pypy 3.6 on macos, which is no longer available.

ci: request explicit pypy version

---

releasenotes/notes/feat-match-short-hash-074e7595ec37967b.yaml
riot/riot.py
tests/test_integration.py
tests/test_unit.py

This allows you to run or list a specific venv instance.
`riot run <hash>`
Fixes  #24

feat: match pattern against VenvInstance name and short hash

---

.github/workflows/codeql-analysis.yml

Static code analysis on riot using Github's Code Scanning.
This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to main branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As the repository is small, no security alerts were found during the scan.

Setting up codescanning for riot

---

riotfile.py

The recently released version of click is incompatible with `black==21.4b2`:
```
Traceback (most recent call last):
File "/home/circleci/project/.riot/venv_py3912_black214b2_isort/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/home/circleci/project/.riot/venv_py3912_black214b2_isort/lib/python3.9/site-packages/black/__init__.py", line 7010, in patched_main
patch_click()
File "/home/circleci/project/.riot/venv_py3912_black214b2_isort/lib/python3.9/site-packages/black/__init__.py", line 6999, in patch_click
from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/circleci/project/.riot/venv_py3912_black214b2_isort/lib/python3.9/site-packages/click/__init__.py)
```

chore: pin click to fix incompatibility

---

releasenotes/notes/feat-use-default-shell-21a39ade10388df5.yaml
riot/riot.py
setup.py

The shell command has been changed to spawn the default shell instead of enforcing the use of bash.

feat: use system default shell

---

releasenotes/notes/fix-shell-use-correct-venv-18f139b392dd26f9.yaml
riot/riot.py
tests/test_integration.py

The shell command defaulted to the base virtual environment. This change ensures that the shell commands activates the corrected created virtual environment.

fix(shell): use correct venv

---

riot/riot.py

mypy doesn't use to work fine with [dataclasses package](https://github.com/python/mypy/issues/9667)
Remove this errors:
```
riot run mypy   
riot/riot.py:238: error: "Venv" has no attribute "env"
riot/riot.py:244: error: "Venv" has no attribute "pys"
riot/riot.py:247: error: "Venv" has no attribute "pkgs"
```

chore(mypy): Fix mypy errors with dataclasses

---

riotfile.py

Set [flake8 version (<5.0.0)](https://pypi.org/project/flake8/#history) until flake8 plugins update their code: https://github.com/pycqa/flake8/issues/325

fix(flake8): new release 5.0 introduces errors in plugins

---

releasenotes/notes/refactor-ensure-dev-in-base-b9c2a3d23d742851.yaml
riot/riot.py
tests/test_integration.py

When running a command for the first time with the `-s` option, the base virtual environments get created, but the installation of the dev package is skipped. This results in import errors when running Python commands against the dev package. This change modified the behaviour of `riot` to ensure that the dev package is always installed when the base virtual environments are generated for the first time. If no dev package is present in the working directory, a warning is issued instead of an error to allow running generic commands without the use of the `-s` option.

refactor!: ensure dev package is installed in base venv

---

releasenotes/notes/fix-use-actual-binary-path-dea292c916d915e5.yaml
riot/riot.py

This change ensures that virtual environments are created with the actual Python binary instead of passing the path to a wrapping script which could cause the creation of inconsistent virtual environments.

fix: use path to actual Python binary

---

releasenotes/notes/fix-recreate-environment-550de176056a0231.yaml
riot/riot.py
tests/data/nested_riotfile.py
tests/setup.py
tests/test_unit.py

`riot` runs `virtualenv [directory]` to create a virtualenv. If `venv 01` directory exists and you run `virtualenv venv01`, the old virtualenv still has the same packages with no reset.
```
python3.8 -m virtualenv -p38 venv_test_38
source venv_test_38/bin/activate 
pip install flask
deactivate
python3.8 -m virtualenv -p38 venv_test_38
source venv_test_38/bin/activate 
pip freeze
```
Output:
```
click==8.1.3
Flask==2.1.3
importlib-metadata==4.12.0
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
Werkzeug==2.1.2
zipp==3.8.1
```

Fix: Ensure a "restart" of virtualenv deleting the old one with recreation option (-r)

---

riotfile.py

This change adds pytest-xdist to the test riot command to run tests in parallel, based on load scope.

test: run tests in parallel

---

riotfile.py

Use the latest version of `black` and stop pinning `click` for tests.
This is a precursor to us removing the version constraint for `click` in `setup.py`.

chore(ci): upgrade black

---

setup.py

After #188 we can now remove the upper constraint on our dependency for `click`.

chore: allow click>=8

---

releasenotes/notes/feat-interpreters-only-flag-for-riot-list-908cc21e85f730b3.yaml
riot/cli.py
riot/riot.py
tests/test_cli.py

This change adds a `-i, --interpreters` flag to the `riot list` command. If set to true, this flag should cause the `riot list` command to output a list of unique python interpreters for each matching venv instead of the overall table that the default command generates.
Example:
```shell
(.venv) riot % riot list test
No.  Hash     Name  Interpreter                Environment  Packages                                                        
#0   51feb80  test  Interpreter(_hint='3.6')   --           'pytest' 'pytest-cov' 'pytest-xdist' 'mock' 'typing-extensions' 
#1   8498bd5  test  Interpreter(_hint='3.7')   --           'pytest' 'pytest-cov' 'pytest-xdist' 'mock' 'typing-extensions' 
#2   1afefb9  test  Interpreter(_hint='3.8')   --           'pytest' 'pytest-cov' 'pytest-xdist' 'mock' …
```

feat: add interpreters flag to riot list command

---

releasenotes/notes/add-list-hash-only-ee2b1414b6b41f72.yaml
riot/cli.py
riot/riot.py
tests/test_cli.py

riot supports doing `riot run <short-hash>`, by offering a way to do `riot list`
and only print the short hashes, we can then support better paralellization in CI.
e.g. `riot list --hash-only | circleci tests split | xargs -n 1 riot -v run`
This would allow us to scale the number of parallel nodes however we want.

feat: add riot list --hash-only option to list only venv short hashes

---

releasenotes/notes/locks-66113372ce122a52.yaml
riot/cli.py
riot/riot.py
tests/test_cli.py
tests/test_integration.py
tests/test_unit.py

This change adds the `riot requirements <hash>` command, which uses pip-compile to generate a requirements lockfile for the venv identified by the hash. It also adds the `-c/--recompile-requirements` flag to `riot run`. When set, this flag causes the requirements.txt lockfile and the venv itself to be regenerated. When omitted, the requirements lockfile is only built if it does not already exist.
This is a useful feature because it reduces duplicated work during `riot run`. In current master, every `riot run` has to build the dependency tree for its venv before installing those dependencies. With this change, the built dependency tree is saved in the form of a lockfile and reused on subsequent `riot run` invocations.

feat: add requirements caching

---

riot/riot.py
tests/test_cli.py
tests/test_integration.py
tests/test_unit.py

This change removes some duplicated work involved in building nested virtualenvs. Because the pip install at the leaf node of a Venv tree installs all of the requirements of that tree, it's redundant to install some requirements again as execution traverses the parent relations. This change causes those parent-Venv installations to be skipped.

chore: don't install requirements in intermediate venvs

---

releasenotes/notes/stable-hash-63389fa04cca60ab.yaml
riot/riot.py
tests/test_cli.py
tests/test_integration.py
tests/test_unit.py

This change removes `self` from the seed used to generate Venv hashes. This is because recent changes to the requirements installation logic mutated `self` between installation and pythonpath generation in such a way as to change the resulting hash. This meant that the virtualenv pointed to in the pythonpath was not the same one that had been generated for the current command run.
Basing the hash solely on attributes that don't change during execution keeps it stable per run.
This has been tested on dd-trace-py https://github.com/DataDog/dd-trace-py/pull/5227/commits/492fc0d8b21e537541befce36ac77478c6ed4f29

fix: change how Venvs are hashed

---

releasenotes/notes/fix-python-2-7-pinning-virtualenv-619b531a9ea8c695.yaml
setup.py

Virtualenv dropped support for Python 2.7, so we need to pin this requirement in order to keep creating 2.7 virtualenvs

fix: pin virtualenv version to 20.20.0

---

releasenotes/notes/emptypkgs-21c00f01a644170d.yaml
riot/riot.py
tests/test_integration.py

This change fixes an issue observable in [this test run](https://app.circleci.com/pipelines/github/DataDog/dd-trace-py/34529/workflows/3cde9cd7-6ea9-4ebc-95a5-a54bf6e9c648/jobs/2334921) in which riot generated a requirements lockfile for a `Venv` instance other than the one it was running tests for. This behavior was happening due to riot logic that skipped `Venv` instances with `pkgs == None` while preparing the environment, but not while running tests. Thus the fix is to stop riot from ignoring `pkgs`-less `Venv`s in all cases.
Note these two lines of output from the example test run:
```
Compiling requirements file .riot/requirements/118238b.in
RIOT_VENV_HASH=32bd6c2
```
This illustrates the mismatch. `RIOT_VENV_HASH` is the hash of the environment in which the command will be run, and …

feat: ensure hash consistency between lockfile and venv

---

releasenotes/notes/fix-preserve-base-venv-d3f406358e593c30.yaml
riot/riot.py
riotfile.py
tests/test_integration.py
tests/test_unit.py

We let riot create an auxiliary venv, suffixed with `_deps`, that is used exclusively for installing dependencies in venv layers. This way we can keep the dev package intact in the base venv.

fix: use dedicated venv for installing dependencies

---

releasenotes/notes/fix-pin-pip-a9a7467675abb679.yaml
riot/riot.py

https://github.com/jazzband/pip-tools/pull/1906 is resolved in pip-tools==7.0.0 which happens to also drop support for Python 3.7. This PR pins pip for Python 3.7.
Error:
https://github.com/DataDog/riot/actions/runs/5520208394/job/15245525172
```
ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze' (/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/pip/_internal/commands/freeze.py)
```

fix: pin pip for pip-tools<7

---

releasenotes/notes/fix-honour-skip-option-46042f082772d5d4.yaml
riot/riot.py
tests/test_integration.py

We fix a regression whereby the skip option was ignored if the base venv did not exist, forcing the installation of the dev package even when requested not to do so.

fix: honour the skip option

---

.github/workflows/main.yml

macos-14 (latest) uses arm64. there aren't python 3.7 builds for that architecture for `actions/setup-python@v4`.

fix(ci): use macos-13 instead of macos-latest

---

releasenotes/notes/allow-unsafe-dff39e7251807993.yaml
riot/riot.py

By default `setuptools` is not included by `pip-compile` generated lock files.
This can cause issues for Venvs which rely on `setuptools` since it won't be included in the lock file.

fix: ensure setuptools is present in riot lock files

---

releasenotes/notes/fix-python-37-virtualenv-e15bd328ac61108d.yaml
setup.py

With the new release of `virtualenv==20.27.0`, we were seeing new failures with `build_base_venv[3.7]` jobs when running:
```
riot -P -v generate --python=$PYTHON_VERSION
...
File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py3717/lib/python3.7/site-packages/pip/_vendor/typing_extensions.py", line 1039
def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
^
SyntaxError: invalid syntax
ERROR:riot.riot:Dev install failed, aborting!
```
We need to pin to `virtualenv==20.26.6` to continue supporting python3.7

ci: pin virtualenv to 20.26.6

---

.github/workflows/build_deploy.yml
.github/workflows/changelog.yml
.github/workflows/main.yml
releasenotes/notes/fix-python-37-virtualenv-e15bd328ac61108d.yaml
setup.py

With the new release of `virtualenv==20.27.0`, we were seeing new failures with `build_base_venv[3.7]` jobs when running:
```
riot -P -v generate --python=$PYTHON_VERSION
...
File "/go/src/github.com/DataDog/apm-reliability/dd-trace-py/.riot/venv_py3717/lib/python3.7/site-packages/pip/_vendor/typing_extensions.py", line 1039
def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
^
SyntaxError: invalid syntax
ERROR:riot.riot:Dev install failed, aborting!
```
We need to pin to `virtualenv==20.26.6` to continue supporting python3.7
The `upload-artifact` and `download-artifact` bumps were required to unblock the riot CI. It had been a while since the last update to riot, and since then, v2 has been deprecated and v3 will be deprecated next month (Nov 2024), so we …

ci: upload,download-artifact v2->v4

---

.github/workflows/build_deploy.yml

We added unique names to the wheel and sdist artifacts in the last change, but that makes the download process fail because it's looking for a single directory with both of these artifacts included, not two individual artifacts.
This change continues to upload the two artifacts with unique names, but we add separate download steps for each artifact since wildcards like `artifact-*` are not supported.
We also needed to give permissions to the job to access secrets.

fix(ci): wheel and sdist artifacts should get uploaded to shared `artifact` dir

---

releasenotes/notes/fix-env-debug-logging-5bf9ff1d5025dcac.yaml
riot/riot.py

Update log to only dump the env variables when debug logging.

fix: only log env variables when debugging logging
